export const BOARD_CHANGE = 'BOARD_CHANGE'

export const GAME_MODE_CHANGE = 'GAME_MODE_CHANGE'

export const GAME_STATE_CHANGE = 'GAME_STATE_CHANGE'

export const EDIT_PLAYER = 'EDIT_PLAYER'

export const NEW_TURN = 'NEW_TURN'

export const UPDATE_WINNING_PLAYER = 'UPDATE_WINNING_PLAYER'

export const RESTART_GAME = 'RESTART_GAME'
